Repository retest/recheck, pull requests merged in 2019-12, with the labels that each got.

#539 Feature/filters to improve sut model
  src/main/java/de/retest/recheck/ui/descriptors/SutStateFilter.java
  src/test/java/de/retest/recheck/ui/descriptors/SutStateFilterTest.java
Labels: cla-signed

#543 Feature/ret 1897 add generic metadata providers
  src/main/java/de/retest/recheck/meta/GlobalMetadataProvider.java
  src/main/java/de/retest/recheck/meta/MetadataProvider.java
  src/main/java/de/retest/recheck/meta/MetadataProviderService.java
  src/main/java/de/retest/recheck/meta/MultiMetadataProvider.java
  src/main/java/de/retest/recheck/persistence/RecheckSutState.java
  src/main/java/de/retest/recheck/ui/descriptors/SutState.java
  src/main/java/de/retest/recheck/ui/descriptors/SutStateFilter.java
  src/test/java/de/retest/recheck/meta/MultiMetadataProviderTest.java
  src/test/java/de/retest/recheck/ui/descriptors/SutStateFilterTest.java
  src/test/java/de/retest/recheck/ui/descriptors/SutStateTest.java
Labels: cla-signed, enhancement

#546 Feature/refactor auth
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/RehubAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
Labels: cla-signed, refactoring

#549 Feature/refactor auth handler
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/AuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/DefaultAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RehubAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
Labels: cla-signed, refactoring

#548 Feature/ret 1898 global metadata
  CHANGELOG.md
  src/main/java/de/retest/recheck/meta/GlobalMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/MachineMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/OSMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/TimeMetadataProvider.java
  src/test/java/de/retest/recheck/meta/GlobalMetadataProviderTest.java
  src/test/java/de/retest/recheck/meta/global/OSMetadataProviderTest.java
  src/test/java/de/retest/recheck/meta/global/TimeMetadataProviderTest.java
  src/test/java/de/retest/recheck/persistence/RecheckSutStateTest.java
Labels: cla-signed, enhancement

#550 Add server-side logout capabilities
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/AuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/DefaultAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RehubAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
Labels: cla-signed

#535 Feature/switch to rhino
  pom.xml
  src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
  src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
Labels: cla-signed

#553 Update changelog for #535
  CHANGELOG.md
Labels: cla-signed

#538 Add RecheckProperties using owner
  pom.xml
  src/main/java/de/retest/recheck/GradleConformFileNamerStrategy.java
  src/main/java/de/retest/recheck/MavenConformFileNamerStrategy.java
  src/main/java/de/retest/recheck/Properties.java
  src/main/java/de/retest/recheck/RecheckImpl.java
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/main/java/de/retest/recheck/RecheckProperties.java
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/configuration/PathBasedProjectRootFinder.java
  src/main/java/de/retest/recheck/configuration/ProjectConfiguration.java
  src/main/java/de/retest/recheck/configuration/ProjectConfigurationUtil.java
  src/main/java/de/retest/recheck/ignore/GloballyIgnoredAttributes.java
  src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
  src/main/java/de/retest/recheck/persistence/FileOutputFormat.java
  src/main/java/de/retest/recheck/persistence/GradleProjectLayout.java
  src/main/java/de/retest/recheck/persistence/MavenProjectLayout.java
  src/main/java/de/retest/recheck/persistence/PersistenceFactory.java
  src/main/java/de/retest/recheck/persistence/RecheckSutState.java
  src/main/java/de/retest/recheck/persistence/RecheckTestReportUtil.java
  src/main/java/de/retest/recheck/persistence/SeparatePathsProjectLayout.java
  src/main/java/de/retest/recheck/persistence/xml/XmlFolderPersistence.java
  src/main/java/de/retest/recheck/persistence/xml/XmlZipPersistence.java
  src/main/java/de/retest/recheck/persistence/xml/util/LazyScreenshotZipPersistence.java
  src/main/java/de/retest/recheck/persistence/xml/util/ScreenshotFolderPersistence.java
  src/main/java/de/retest/recheck/ui/TargetFinder.java
  src/main/java/de/retest/recheck/ui/diff/Alignment.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifferenceFinder.java
  src/test/java/de/retest/recheck/GradleConformFileNamerStrategyTest.java
  src/test/java/de/retest/recheck/MavenConformFileNamerStrategyTest.java
  src/test/java/de/retest/recheck/RecheckImplTest.java
  src/test/java/de/retest/recheck/RecheckPropertiesTest.java
  src/test/java/de/retest/recheck/configuration/ProjectConfigurationTest.java
  src/test/java/de/retest/recheck/ignore/SearchFilterFilesTest.java
  src/test/java/de/retest/recheck/persistence/RecheckTestReportUtilTest.java
  src/test/java/de/retest/recheck/review/workers/LoadAndSaveFilterWorkerTest.java
  src/test/java/de/retest/recheck/ui/TargetFinderTest.java
Labels: cla-signed

#554 Feature/use system utils
  src/main/java/de/retest/recheck/meta/global/MachineMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/OSMetadataProvider.java
Labels: cla-signed, enhancement

#555 Feature/fix xpath matcher
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementXPathMatcher.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementXPathMatcherTest.java
  src/test/java/de/retest/recheck/ui/PathTest.java
  src/test/resources/de/retest/recheck/review/workers/recheck.ignore
Labels: cla-signed

#556 Using the actual element is even _less_ code and more realistic
  src/test/java/de/retest/recheck/review/ignore/AttributeFilterTest.java
  src/test/java/de/retest/recheck/review/ignore/ElementFilterLoaderTest.java
Labels: cla-signed

#545 Feature/ret 1900 compare metadata to report
  CHANGELOG.md
  src/main/java/de/retest/recheck/execution/RecheckDifferenceFinder.java
  src/main/java/de/retest/recheck/report/ActionReplayResult.java
  src/main/java/de/retest/recheck/report/TestReport.java
  src/main/java/de/retest/recheck/report/TestReportFilter.java
  src/main/java/de/retest/recheck/report/action/DifferenceRetriever.java
  src/main/java/de/retest/recheck/ui/diff/DifferenceResult.java
  src/main/java/de/retest/recheck/ui/diff/meta/MetadataDifference.java
  src/main/java/de/retest/recheck/ui/diff/meta/MetadataDifferenceFinder.java
  src/main/java/de/retest/recheck/ui/diff/meta/MetadataElementDifference.java
  src/test/java/de/retest/recheck/execution/RecheckDifferenceFinderTest.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
  src/test/java/de/retest/recheck/report/TestReportFilterTest.java
  src/test/java/de/retest/recheck/ui/diff/meta/MetadataDifferenceFinderTest.java
  src/test/java/de/retest/recheck/ui/diff/meta/MetadataDifferenceTest.java
Labels: cla-signed, enhancement

#559 Using the actual element is even _less_ code and more realistic
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcherTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementIdMatcherLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementIdMatcherTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementTypeMatcherTest.java
Labels: cla-signed

#563 Properly name recheck version
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/main/java/de/retest/recheck/persistence/xml/ReTestXmlDataContainer.java
  src/main/java/de/retest/recheck/util/VersionProvider.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
  src/test/java/de/retest/recheck/persistence/xml/ReTestXmlDataContainerTest.java
  src/test/java/de/retest/recheck/util/VersionProviderTest.java
Labels: cla-signed, refactoring

#564 Fix properties
  src/main/java/de/retest/recheck/RecheckProperties.java
  src/main/java/de/retest/recheck/Rehub.java
  src/test/java/de/retest/recheck/RecheckPropertiesTest.java
  src/test/java/de/retest/recheck/persistence/PersistenceFactoryTest.java
  src/test/resources/persistence/empty.zip
Labels: cla-signed

#560 Feature/refactorings
  src/main/java/de/retest/recheck/report/TestReportFilter.java
  src/main/java/de/retest/recheck/review/ignore/PixelDiffFilter.java
  src/main/java/de/retest/recheck/ui/descriptors/AttributeUtil.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifference.java
Labels: cla-signed

#552 Feature/read ignore in user home
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/main/java/de/retest/recheck/configuration/ProjectConfigurationUtil.java
  src/main/java/de/retest/recheck/ignore/RecheckIgnoreUtil.java
  src/main/java/de/retest/recheck/review/workers/LoadFilterWorker.java
  src/main/java/de/retest/recheck/review/workers/SaveFilterWorker.java
  src/test/java/de/retest/recheck/review/workers/LoadFilterWorkerTest.java
Labels: cla-signed

#551 Add GIT metadata
  CHANGELOG.md
  src/main/java/de/retest/recheck/meta/global/GitMetadataProvider.java
  src/main/java/de/retest/recheck/persistence/GitExecutor.java
  src/test/java/de/retest/recheck/meta/global/GitMetadataProviderTest.java
  src/test/java/de/retest/recheck/persistence/GitExecutorTest.java
Labels: cla-signed

#566 Add method 'getRootElement' and test
  src/main/java/de/retest/recheck/ui/descriptors/Element.java
  src/test/java/de/retest/recheck/ui/descriptors/ElementTest.java
Labels: cla-signed

#547 Feature/let metadata overwrite others
  src/main/java/de/retest/recheck/meta/MetadataProvider.java
  src/main/java/de/retest/recheck/meta/MetadataProviderService.java
  src/main/java/de/retest/recheck/meta/MultiMetadataProvider.java
  src/test/java/de/retest/recheck/meta/MetadataProviderServiceTest.java
  src/test/java/de/retest/recheck/meta/MultiMetadataProviderTest.java
Labels: cla-signed, enhancement

#565 Feature/ret 1902 print metadata
  CHANGELOG.md
  src/main/java/de/retest/recheck/printer/ActionReplayResultPrinter.java
  src/main/java/de/retest/recheck/printer/MetadataDifferencePrinter.java
  src/main/java/de/retest/recheck/printer/TestReplayResultPrinter.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/printer/MetadataDifferencePrinterTest.java
  src/test/java/de/retest/recheck/printer/SuiteReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/printer/TestReplayResultPrinterTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
Labels: cla-signed, enhancement

#570 Feature/fix git metadata provider
  src/main/java/de/retest/recheck/meta/GlobalMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/GitMetadataProvider.java
  src/main/java/de/retest/recheck/meta/global/TimeMetadataProvider.java
Labels: bug, cla-signed

#571 Feature/make printer ignore instead of allow
  src/main/java/de/retest/recheck/printer/ActionReplayResultPrinter.java
  src/main/java/de/retest/recheck/printer/MetadataDifferencePrinter.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/printer/MetadataDifferencePrinterTest.java
Labels: cla-signed, enhancement

#568 Support external auth configuration
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
Labels: cla-signed

#572 Add test from review that belongs here and fix it
  src/main/java/de/retest/recheck/report/action/DifferenceRetriever.java
  src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
Labels: cla-signed

#569 Add Mergify config
  .mergify.yml
Labels: cla-signed

#573 Feature/refactor action replay result
  src/main/java/de/retest/recheck/NoGoldenMasterActionReplayResult.java
  src/main/java/de/retest/recheck/printer/ActionReplayResultPrinter.java
  src/main/java/de/retest/recheck/printer/TestReplayResultPrinter.java
  src/main/java/de/retest/recheck/report/ActionReplayResult.java
  src/main/java/de/retest/recheck/report/SuiteReplayResult.java
  src/main/java/de/retest/recheck/report/TestReport.java
  src/main/java/de/retest/recheck/report/action/ErrorHolder.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
Labels: cla-signed, refactoring

#574 Feature/fix metadata
  src/main/java/de/retest/recheck/RecheckImpl.java
  src/main/java/de/retest/recheck/execution/RecheckDifferenceFinder.java
  src/main/java/de/retest/recheck/printer/MetadataDifferencePrinter.java
  src/main/java/de/retest/recheck/ui/diff/meta/MetadataDifference.java
  src/test/java/de/retest/recheck/execution/RecheckDifferenceFinderTest.java
  src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
Labels: bug, cla-signed

#558 Feature/migrate pixel diff filter
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/ignore/PixelDiffFilter.java
  src/test/java/de/retest/recheck/review/ignore/PixelDiffFilterLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/PixelDiffFilterTest.java
  src/test/resources/de/retest/recheck/review/workers/recheck.ignore
Labels: cla-signed

#575 Fix defaults
  src/main/resources/default-recheck.ignore
  src/main/resources/default-recheck.ignore.js
  src/main/resources/default-retest.properties
Labels: cla-signed

#578 Fix/valid version not recognized
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
Labels: cla-signed

#576 Add missing changelog entry
  CHANGELOG.md
Labels: cla-signed

#577 Fix errors for non git projects
  src/main/java/de/retest/recheck/persistence/GitExecutor.java
  src/test/java/de/retest/recheck/meta/global/GitMetadataProviderTest.java
  src/test/java/de/retest/recheck/persistence/GitExecutorTest.java
Labels: cla-signed

#579 Consider requested changes
  .mergify.yml
Labels: cla-signed

#580 Finalize changelog for release
  CHANGELOG.md
Labels: cla-signed

#581 Release/v1.8.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/retest/recheck/persistence/GitExecutor.java
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/main/resources/default-recheck.ignore
  src/main/resources/default-recheck.ignore.js
  src/main/resources/default-retest.properties
  src/test/java/de/retest/recheck/meta/global/GitMetadataProviderTest.java
  src/test/java/de/retest/recheck/persistence/GitExecutorTest.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
Labels: cla-signed

#567 Refactor alignment
  src/main/java/de/retest/recheck/ui/descriptors/IdentifyingAttributes.java
  src/main/java/de/retest/recheck/ui/diff/Alignment.java
  src/main/java/de/retest/recheck/ui/diff/ElementDifferenceFinder.java
  src/main/java/de/retest/recheck/ui/diff/Match.java
  src/main/java/de/retest/recheck/util/StringSimilarity.java
  src/test/java/de/retest/recheck/ui/diff/AlignmentTest.java
  src/test/java/de/retest/recheck/ui/diff/MatchTest.java
Labels: cla-signed

#585 Feature/evaluate project root
  CHANGELOG.md
  src/main/java/de/retest/recheck/configuration/ProjectConfiguration.java
Labels: cla-signed, enhancement

#586 Add jitpack badge to readme
  README.md
Labels: cla-signed

#590 Add deprecation warning
  src/main/java/de/retest/recheck/FileNamerStrategy.java
Labels: cla-signed
