Repository retest/recheck, pull requests merged in 2019-11, with the labels that each got.

#496 Separate soon-to-be-released features etc.
  CHANGELOG.md
Labels: cla-signed

#489 Feature/fix illegal reflection
  src/main/java/de/retest/recheck/ui/image/ImageUtils.java
  src/test/java/de/retest/recheck/ui/image/ImageUtilsTest.java
Labels: cla-signed

#499 Put the file content correctly into the body
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
Labels: bug, cla-signed

#494 Add some attributes that should be ignored by default...
  CHANGELOG.md
  src/main/resources/default-recheck.ignore
  src/test/java/DefaultRecheckIgnoreTest.java
Labels: cla-signed

#500 Fix/screenshot changes without differences
  src/main/java/de/retest/recheck/ui/review/ScreenshotChanges.java
  src/test/java/de/retest/recheck/ui/review/ScreenshotChangesTest.java
Labels: bug, cla-signed

#503 Prepare changelog for release
  CHANGELOG.md
Labels: cla-signed

#504 Release/v1.6.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
  src/main/java/de/retest/recheck/persistence/NoGoldenMasterFoundException.java
  src/main/java/de/retest/recheck/ui/diff/StateDifference.java
  src/main/java/de/retest/recheck/ui/image/ImageUtils.java
  src/main/java/de/retest/recheck/ui/review/ScreenshotChanges.java
  src/main/resources/default-recheck.ignore
  src/test/java/DefaultRecheckIgnoreTest.java
  src/test/java/de/retest/recheck/persistence/NoGoldenMasterFoundExceptionTest.java
  src/test/java/de/retest/recheck/ui/image/ImageUtilsTest.java
  src/test/java/de/retest/recheck/ui/review/ScreenshotChangesTest.java
  src/test/java/de/retest/suite/flow/ApplyChangesToStatesFlowTest.java
  src/test/java/de/retest/suite/flow/CreateChangesetForAllDiffrencesFlowTest.java
Labels: cla-signed

#493 Ignore elements based on retestId rather than XPath
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/GlobalIgnoreApplier.java
  src/test/java/de/retest/recheck/review/GlobalIgnoreApplierTest.java
Labels: cla-signed

#507 Add the code of conduct
  CODE_OF_CONDUCT.md
Labels: cla-signed, enhancement

#508 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
Labels: cla-signed, enhancement

#509 Remove unsupported yaml header
  .github/pull_request_template.md
Labels: bug, cla-signed

#510 Delegate to the retest docs
  CODE_OF_CONDUCT.md
Labels: cla-signed, enhancement

#511 Add contributing guidelines
  CONTRIBUTING.md
Labels: cla-signed, enhancement

#513 Fix .travis.yml
  .travis.yml
Labels: cla-signed

#497 Feature/improve internal structure
  src/main/java/de/retest/recheck/RecheckImpl.java
Labels: cla-signed

#512 Feature/rework filter loader mechanism
  src/main/java/de/retest/recheck/ignore/CacheFilter.java
  src/main/java/de/retest/recheck/ignore/Filters.java
  src/main/java/de/retest/recheck/review/ignore/AttributeFilter.java
  src/main/java/de/retest/recheck/review/ignore/AttributeRegexFilter.java
  src/main/java/de/retest/recheck/review/ignore/ElementAttributeFilter.java
  src/main/java/de/retest/recheck/review/ignore/ElementAttributeRegexFilter.java
  src/main/java/de/retest/recheck/review/ignore/ElementFilter.java
  src/main/java/de/retest/recheck/review/ignore/FilterPreserveLineLoader.java
  src/main/java/de/retest/recheck/review/ignore/JSFilterLoader.java
  src/main/java/de/retest/recheck/review/ignore/PixelDiffFilter.java
  src/main/java/de/retest/recheck/review/ignore/io/ErrorHandlingLoader.java
  src/main/java/de/retest/recheck/review/ignore/io/InheritanceLoader.java
  src/main/java/de/retest/recheck/review/ignore/io/Loader.java
  src/main/java/de/retest/recheck/review/ignore/io/Loaders.java
  src/main/java/de/retest/recheck/review/ignore/io/RegexLoader.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcher.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementIdMatcher.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementRetestIdMatcher.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementTypeMatcher.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementXPathMatcher.java
  src/main/java/de/retest/recheck/review/workers/LoadFilterWorker.java
  src/main/java/de/retest/recheck/review/workers/SaveFilterWorker.java
  src/test/java/de/retest/recheck/review/ignore/ElementAttributeFilterLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/ElementFilterLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/FilterPreserveLineTest.java
  src/test/java/de/retest/recheck/review/ignore/PixelDiffFilterLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/io/InheritanceLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/io/LoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcherLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementIdMatcherLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementRetestIdMatcherLoaderTest.java
Labels: cla-signed, refactoring

#516 Feature/improve filters
  src/main/resources/filter/web/content.filter
  src/main/resources/filter/web/invisible-attributes.filter
  src/test/java/de/retest/recheck/ignore/ContentFilterIT.java
Labels: cla-signed

#517 Make sure that the default-recheck.ignore.js file loaded without errors
  src/test/java/DefaultRecheckIgnoreJsTest.java
Labels: cla-signed

#519 Feature/add suite description
  CHANGELOG.md
  src/main/java/de/retest/recheck/printer/SuiteReplayResultPrinter.java
  src/test/java/de/retest/recheck/printer/SuiteReplayResultPrinterTest.java
Labels: cla-signed, enhancement

#505 Feature/js filter log cache
  CHANGELOG.md
  src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
  src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
Labels: cla-signed

#520 Feature/add version check to persistence
  CHANGELOG.md
  src/main/java/de/retest/recheck/ioerror/ReTestIOException.java
  src/main/java/de/retest/recheck/ioerror/ReTestLoadException.java
  src/main/java/de/retest/recheck/persistence/IncompatibleReportVersionException.java
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/main/java/de/retest/recheck/report/TestReport.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
  src/test/resources/de/retest/recheck/persistence/bin/1.6.0.report
Labels: bug, cla-signed, enhancement

#522 Do not wrap NoSuchFileException inside a IncompatibleReportVersionExc…
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
Labels: bug, cla-signed

#524 Fix/log flooding
  src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
  src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
Labels: cla-signed

#525 Prepare changelog
  CHANGELOG.md
Labels: cla-signed

#526 Release/v1.7.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
  src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
  src/test/java/de/retest/recheck/persistence/bin/KryoPersistenceTest.java
Labels: cla-signed

#528 Log where ignore file was loaded from
  src/main/java/de/retest/recheck/review/workers/LoadFilterWorker.java
Labels: cla-signed

#532 Odd that this was formatted like that
  src/main/java/de/retest/recheck/persistence/RecheckSutState.java
Labels: cla-signed

#533 Add 'target', 'rel', 'xmlns' and 'scale' as attributes
  CHANGELOG.md
  src/main/resources/filter/web/invisible-attributes.filter
  src/main/resources/filter/web/style-attributes.filter
Labels: cla-signed

#534 Feature/revise filter interface
  src/main/java/de/retest/recheck/ignore/CacheFilter.java
  src/main/java/de/retest/recheck/ignore/Filter.java
  src/main/java/de/retest/recheck/ignore/FilterOutline.java
  src/main/java/de/retest/recheck/review/ignore/AttributeFilter.java
  src/main/java/de/retest/recheck/review/ignore/AttributeRegexFilter.java
  src/main/java/de/retest/recheck/review/ignore/ElementAttributeFilter.java
  src/main/java/de/retest/recheck/review/ignore/ElementAttributeRegexFilter.java
  src/test/java/de/retest/recheck/ignore/CacheFilterTest.java
  src/test/java/de/retest/recheck/ignore/FilterLoaderTest.java
  src/test/java/de/retest/recheck/report/TestReportFilterTest.java
  src/test/java/de/retest/recheck/review/ignore/AttributeFilterTest.java
  src/test/java/de/retest/recheck/review/ignore/ElementAttributeFilterTest.java
Labels: cla-signed

#536 Feature/adapt compound filter
  src/main/java/de/retest/recheck/ignore/CompoundFilter.java
  src/test/java/de/retest/recheck/ignore/CompoundFilterTest.java
Labels: cla-signed

#540 Feature/delete deprecated methods
  src/main/java/de/retest/recheck/NoGoldenMasterActionReplayResult.java
  src/main/java/de/retest/recheck/report/ActionReplayResult.java
  src/main/java/de/retest/recheck/report/TestReplayResult.java
  src/main/java/de/retest/recheck/review/AcceptableElementDifference.java
  src/main/java/de/retest/recheck/ui/diff/ElementDifference.java
  src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
Labels: cla-signed

#537 Feature/add meta data
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckAdapter.java
  src/main/java/de/retest/recheck/persistence/RecheckSutState.java
  src/main/java/de/retest/recheck/ui/descriptors/SutState.java
  src/main/java/de/retest/recheck/ui/review/ActionChangeSet.java
  src/test/java/de/retest/recheck/persistence/RecheckSutStateTest.java
  src/test/java/de/retest/recheck/ui/descriptors/SutStateTest.java
  src/test/resources/de/retest/util/XsdRegressionTest.checkXsd/ExecutableSuite.approved.xsd
Labels: cla-signed

#530 Have public save and load methods, such that they can be used by Babelfish
  src/main/java/de/retest/recheck/persistence/bin/KryoPersistence.java
Labels: cla-signed
