Repository retest/recheck, pull requests merged in 2019-10, with the labels that each got.

#449 Feature/ignore pixel box shadow
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/ignore/PixelDiffFilter.java
  src/test/java/de/retest/recheck/review/ignore/PixelDiffFilterTest.java
Labels: bug, cla-signed

#451 Feature/update screenshots
  CHANGELOG.md
  src/main/java/de/retest/recheck/suite/flow/CreateChangesetForAllDifferencesFlow.java
  src/main/java/de/retest/recheck/ui/descriptors/RootElement.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifferenceFinder.java
  src/main/java/de/retest/recheck/ui/review/ActionChangeSet.java
  src/main/java/de/retest/recheck/ui/review/ScreenshotChanges.java
  src/main/java/de/retest/recheck/ui/review/TestChangeSet.java
  src/test/java/de/retest/recheck/ui/descriptors/ActionChangeSetTestUtils.java
  src/test/java/de/retest/recheck/ui/descriptors/RootElementTest.java
  src/test/java/de/retest/suite/flow/ApplyChangesToStatesFlowTest.java
  src/test/java/de/retest/suite/flow/CreateChangesetForAllDiffrencesFlowTest.java
Labels: cla-signed

#450 Move evaluation of suite name into builder.
  src/main/java/de/retest/recheck/RecheckImpl.java
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/test/java/de/retest/recheck/RecheckOptionsTest.java
Labels: cla-signed

#453 Friendly report upload name
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
  src/main/java/de/retest/recheck/persistence/ReportUploadMetadata.java
Labels: cla-signed

#454 Feature/diff tests
  src/main/java/de/retest/recheck/ui/diff/AttributeDifference.java
  src/main/java/de/retest/recheck/ui/diff/AttributesDifference.java
  src/main/java/de/retest/recheck/ui/diff/ElementDifference.java
  src/main/java/de/retest/recheck/ui/diff/ElementDifferenceFinder.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifferenceFinder.java
  src/main/java/de/retest/recheck/ui/diff/StateDifference.java
  src/test/java/de/retest/recheck/ui/diff/AlignmentTest.java
  src/test/java/de/retest/recheck/ui/diff/AttributeDifferenceTest.java
  src/test/java/de/retest/recheck/ui/diff/AttributesDifferenceFinderTest.java
  src/test/java/de/retest/recheck/ui/diff/DurationDifferenceTest.java
  src/test/java/de/retest/recheck/ui/diff/ElementBuilder.java
  src/test/java/de/retest/recheck/ui/diff/ElementDifferenceFinderTest.java
  src/test/java/de/retest/recheck/ui/diff/ElementDifferenceTest.java
  src/test/java/de/retest/recheck/ui/diff/MatchTest.java
  src/test/java/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.java
  src/test/java/de/retest/recheck/ui/diff/RootElementDifferenceTest.java
  src/test/java/de/retest/recheck/ui/diff/StateDifferenceTest.java
  src/test/resources/de/retest/recheck/ui/diff/DurationDifferenceTest.expected_is_shorter_and_above_threshold.approved.xml
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.actual_root_element_is_null.approved.txt
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.different_root_element_with_same_components_should_match.approved.txt
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.expected_and_actual_root_element_are_different.approved.txt
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.expected_root_element_is_null.approved.txt
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.lists_of_different_root_element_are_matched_even_if_the_order_is_different.approved.txt
  src/test/resources/de/retest/recheck/ui/diff/RootElementDifferenceFinderTest.lists_of_root_element_with_different_window_titles_are_not_matched.approved.txt
Labels: cla-signed

#458 Use LogUnit to test logs in JUnit 5 tests
  pom.xml
  src/test/java/de/retest/recheck/ui/diff/AttributeDifferenceTest.java
Labels: cla-signed

#455 Feature/configurable window match
  src/main/java/de/retest/recheck/Properties.java
  src/main/java/de/retest/recheck/ui/diff/Alignment.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifferenceFinder.java
Labels: cla-signed

#456 A filter.js file should be loaded as JavaScript filter
  src/main/java/de/retest/recheck/ignore/FilterLoader.java
  src/test/java/de/retest/recheck/ignore/FilterLoaderTest.java
  src/test/java/de/retest/recheck/ignore/FiltersTest.java
  src/test/resources/de/retest/recheck/ignore/file.filter.js
Labels: cla-signed

#460 Element class matcher
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/ignore/io/ErrorHandlingLoader.java
  src/main/java/de/retest/recheck/review/ignore/io/Loaders.java
  src/main/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcher.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcherLoaderTest.java
  src/test/java/de/retest/recheck/review/ignore/matcher/ElementClassMatcherTest.java
  src/test/java/de/retest/recheck/review/workers/LoadAndSaveFilterWorkerTest.java
  src/test/resources/de/retest/recheck/review/workers/recheck.ignore
Labels: cla-signed

#461 Feature/add reflection utilities has method
  src/main/java/de/retest/recheck/util/ReflectionUtilities.java
  src/test/java/de/retest/recheck/util/ReflectionUtilitiesTest.java
  src/test/java/de/retest/recheck/util/VersionProviderTest.java
Labels: cla-signed

#467 Feature/misc
  README.md
  ci/script.sh
  pom.xml
Labels: cla-signed

#472 Improve cap test
  src/main/java/de/retest/recheck/RecheckImpl.java
Labels: cla-signed

#473 Let parent of `RootElement` be null
  src/main/java/de/retest/recheck/ui/descriptors/Element.java
  src/main/java/de/retest/recheck/ui/descriptors/RootElement.java
  src/test/java/de/retest/recheck/ui/descriptors/RootElementTest.java
Labels: cla-signed

#474 Feature/sonarcloud changes
  src/main/java/de/retest/recheck/Properties.java
  src/main/java/de/retest/recheck/XmlTransformerUtil.java
  src/main/java/de/retest/recheck/execution/RecheckDifferenceFinder.java
  src/main/java/de/retest/recheck/ignore/Filters.java
  src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
  src/main/java/de/retest/recheck/logging/LogUtil.java
  src/main/java/de/retest/recheck/persistence/ClassAndMethodBasedShortNamingStrategy.java
  src/main/java/de/retest/recheck/persistence/migration/XmlMigrator.java
Labels: cla-signed

#477 Fix state diff tests
  src/main/java/de/retest/recheck/XmlTransformerUtil.java
  src/main/java/de/retest/recheck/persistence/xml/XmlTransformer.java
  src/main/java/de/retest/recheck/persistence/xml/XmlTransformerConfiguration.java
  src/test/java/de/retest/recheck/ui/diff/StateDifferenceTest.java
Labels: cla-signed

#466 Fix NPE as reported ...
  src/main/java/de/retest/recheck/report/ActionReplayResult.java
Labels: cla-signed

#463 Feature/move props to opts
  src/main/java/de/retest/recheck/RecheckAdapter.java
  src/main/java/de/retest/recheck/RecheckImpl.java
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/main/java/de/retest/recheck/execution/RecheckAdapters.java
  src/test/java/de/retest/recheck/execution/RecheckAdaptersTest.java
Labels: cla-signed

#480 Otherwise we get an UIException if the file exists
  src/test/java/de/retest/recheck/util/ApprovalsUtil.java
Labels: cla-signed

#481 Feature/warning improvement
  src/main/java/de/retest/recheck/ui/diff/ElementIdentificationWarning.java
  src/test/resources/de/retest/util/XsdRegressionTest.checkXsd/AttributeDifference.approved.xsd
  src/test/resources/de/retest/util/XsdRegressionTest.checkXsd/AttributesDifference.approved.xsd
  src/test/resources/de/retest/util/XsdRegressionTest.checkXsd/IdentifyingAttributesDifference.approved.xsd
  src/test/resources/de/retest/util/XsdRegressionTest.checkXsd/ScreenshotAttributeDifference.approved.xsd
Labels: cla-signed

#478 Feature/simple screenshotfilename
  CHANGELOG.md
  src/main/java/de/retest/recheck/persistence/xml/util/ScreenshotFolderPersistence.java
  src/main/java/de/retest/recheck/ui/diff/ElementDifference.java
  src/main/java/de/retest/recheck/ui/diff/RootElementDifference.java
  src/main/java/de/retest/recheck/ui/image/ImageUtils.java
  src/main/java/de/retest/recheck/ui/image/Screenshot.java
  src/test/java/de/retest/recheck/image/ScreenshotTest.java
  src/test/java/de/retest/recheck/persistence/xml/util/ScreenshotFolderPersistenceTest.java
  src/test/java/de/retest/recheck/ui/image/ScreenshotTest.java
Labels: cla-signed

#484 Add a convenience method to return the value of an attribute
  src/main/java/de/retest/recheck/ui/descriptors/Element.java
  src/test/java/de/retest/recheck/ui/descriptors/ElementTest.java
Labels: cla-signed

#486 Improve log
  src/main/java/de/retest/recheck/ui/diff/AttributeDifference.java
  src/test/java/de/retest/recheck/ui/diff/AttributeDifferenceTest.java
Labels: cla-signed

#490 Fix/screenshot changes with nulls
  src/main/java/de/retest/recheck/ui/review/ScreenshotChanges.java
  src/test/java/de/retest/recheck/ui/review/ScreenshotChangesTest.java
Labels: bug, cla-signed

#491 Revert past delete of "unused" method
  src/main/java/de/retest/recheck/ui/diff/StateDifference.java
Labels: cla-signed

#492 Fix/properly format no golden master
  src/main/java/de/retest/recheck/persistence/NoGoldenMasterFoundException.java
  src/test/java/de/retest/recheck/persistence/NoGoldenMasterFoundExceptionTest.java
  src/test/java/de/retest/suite/flow/ApplyChangesToStatesFlowTest.java
  src/test/java/de/retest/suite/flow/CreateChangesetForAllDiffrencesFlowTest.java
Labels: cla-signed, enhancement
