Repository retest/recheck, pull requests merged in 2020-03, with the labels that each got.

#668 Feature/name in retest
  CHANGELOG.md
  src/main/java/de/retest/recheck/ui/descriptors/idproviders/AbstractFirstNonNullRetestIdProvider.java
  src/test/java/de/retest/recheck/ui/descriptors/idproviders/DefaultRetestIdProviderTest.java
Labels: cla-signed

#667 Feature/adapt element diff printer
  src/main/java/de/retest/recheck/printer/ElementDifferencePrinter.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_with_deleted_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/printer/ActionReplayResultPrinterTest.toString_should_not_print_child_differences_if_insertion_or_deletion.approved.txt
Labels: cla-signed

#669 Finalize changelog for release
  CHANGELOG.md
Labels: cla-signed

#670 Release/v1.10.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/retest/recheck/printer/ElementDifferencePrinter.java
  src/main/java/de/retest/recheck/ui/descriptors/idproviders/AbstractFirstNonNullRetestIdProvider.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/ui/descriptors/idproviders/DefaultRetestIdProviderTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_with_deleted_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/printer/ActionReplayResultPrinterTest.toString_should_not_print_child_differences_if_insertion_or_deletion.approved.txt
Labels: cla-signed

#672 Fix missing coverage for SonarCloud
  ci/script.sh
  pom.xml
Labels: cla-signed

#674 Feature/simplify mergify
  .mergify.yml
Labels: cla-signed, enhancement

#676 Fix/import filter
  src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
  src/test/java/de/retest/recheck/ignore/SearchFilterFilesTest.java
Labels: bug, cla-signed

#675 Feature/update auth config
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
Labels: cla-signed

#677 Prepare changelog for release 1.10.1
  CHANGELOG.md
Labels: cla-signed

#678 Hotfix/v1.10.1
  CHANGELOG.md
  src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
  src/test/java/de/retest/recheck/ignore/SearchFilterFilesTest.java
Labels: cla-signed

#671 Feature/filter description
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/main/java/de/retest/recheck/ignore/Filter.java
  src/main/java/de/retest/recheck/ui/descriptors/SutStateFilter.java
  src/test/java/de/retest/recheck/RecheckImplIT.java
  src/test/java/de/retest/recheck/ui/descriptors/SutStateFilterTest.java
Labels: cla-signed

#681 Fix/use friendly url
  CHANGELOG.md
  src/main/java/de/retest/recheck/Rehub.java
  src/main/java/de/retest/recheck/auth/RetestAuthentication.java
Labels: bug, cla-signed

#682 Prepare changelog for release 1.10.2
  CHANGELOG.md
Labels: cla-signed

#683 Feature/minor cleanups
  src/main/java/de/retest/recheck/auth/DefaultAuthenticationHandler.java
  src/main/java/de/retest/recheck/auth/RehubAuthenticationHandler.java
  src/main/java/de/retest/recheck/persistence/GitExecutor.java
  src/main/java/de/retest/recheck/util/OptionalUtil.java
  src/test/java/de/retest/recheck/util/OptionalUtilTest.java
Labels: cla-signed

#684 Hotfix/v1.10.2
  CHANGELOG.md
Labels: cla-signed

#686 Feature/cleanup datamodel
  src/main/java/de/retest/recheck/ui/actions/AbstractAction.java
  src/main/java/de/retest/recheck/ui/actions/Action.java
  src/main/java/de/retest/recheck/ui/actions/ActionIdentifyingAttributes.java
  src/main/java/de/retest/recheck/util/ListMap.java
  src/main/java/de/retest/recheck/util/Mapping.java
Labels: cla-signed

#687 Add exception handling for report upload
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
Labels: cla-signed

#688 Update default filters with some more
  src/main/resources/filter/web/content.filter
  src/main/resources/filter/web/invisible-attributes.filter
  src/main/resources/filter/web/style-attributes.filter
Labels: cla-signed

#689 RandomSuffixRetestIdProvider is now obsolete and even misleading...
  CHANGELOG.md
  src/main/java/de/retest/recheck/ui/descriptors/idproviders/RandomSuffixRetestIdProvider.java
  src/test/java/de/retest/recheck/ui/descriptors/idproviders/RandomSuffixRetestIdProviderTest.java
Labels: cla-signed

#690 Well, tabindex is actually the correct attribute
  src/main/resources/filter/web/invisible-attributes.filter
Labels: cla-signed

#691 Feature/improve outline handling
  CHANGELOG.md
  src/main/java/de/retest/recheck/ui/descriptors/AttributeUtil.java
  src/main/java/de/retest/recheck/ui/image/ImageUtils.java
  src/test/java/de/retest/recheck/ui/descriptors/AttributeUtilTest.java
Labels: cla-signed

#699 Min-width and height and vertical align are also positioning attributes
  src/main/resources/filter/web/positioning.filter
Labels: cla-signed

#705 Improve ElementUtil
  src/main/java/de/retest/recheck/ui/descriptors/ElementUtil.java
  src/test/java/de/retest/recheck/ui/descriptors/ElementUtilTest.java
Labels: cla-signed
