Repository retest/recheck, pull requests merged in 2020-07, with the labels that each got.

#750 Fix/attribute null
  CHANGELOG.md
  src/main/java/de/retest/recheck/ui/descriptors/IdentifyingAttributes.java
  src/test/java/de/retest/recheck/ui/descriptors/IdentifyingAttributesTest.java
Labels: bug, cla-signed

#751 Hotfix/v1.11.2
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/GlobalChangeSetApplier.java
  src/main/java/de/retest/recheck/ui/descriptors/IdentifyingAttributes.java
  src/main/java/de/retest/recheck/ui/diff/AttributeDifference.java
  src/test/java/de/retest/recheck/review/GlobalChangeSetApplierIT.java
  src/test/java/de/retest/recheck/review/GlobalChangeSetApplierTest.java
  src/test/java/de/retest/recheck/ui/descriptors/IdentifyingAttributesTest.java
Labels: cla-signed

#753 Override method to match attribute key
  src/main/java/de/retest/recheck/review/GlobalIgnoreApplier.java
Labels: cla-signed

#755 We don't _need_ a file for every state, thus it's not missing...
  src/main/java/de/retest/recheck/review/workers/LoadFilterWorker.java
Labels: cla-signed

#760 Allow to disable the uploading to rehub on individual tests...
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckOptions.java
Labels: cla-signed

#758 Make the output much less verbose in terms of whitespace used...
  CHANGELOG.md
  src/main/java/de/retest/recheck/printer/AttributeDifferencePrinter.java
  src/main/java/de/retest/recheck/printer/MetadataDifferencePrinter.java
  src/test/java/de/retest/recheck/printer/ActionReplayResultPrinterTest.java
  src/test/java/de/retest/recheck/printer/ElementDifferencePrinterTest.java
  src/test/java/de/retest/recheck/printer/MetadataDifferencePrinterTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_with_deleted_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/printer/ActionReplayResultPrinterTest.toString_should_not_print_child_differences_if_insertion_or_deletion.approved.txt
Labels: cla-signed

#759 Feature/reduce redundancy
  src/main/java/de/retest/recheck/review/ignore/ChainableFilterLoaderUtil.java
  src/main/java/de/retest/recheck/review/ignore/MatcherFilter.java
  src/test/java/de/retest/recheck/review/ignore/MatcherFilterLoaderTest.java
Labels: cla-signed

#756 Add metadata for web, that should also be ignored on default...
  CHANGELOG.md
  src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
  src/main/resources/default-recheck.ignore
  src/main/resources/filter/metadata.filter
  src/main/resources/filter/volatile-metadata.filter
  src/test/java/de/retest/recheck/RecheckImplIT.java
  src/test/java/de/retest/recheck/ignore/SearchFilterFilesTest.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_if_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_be_created_with_deleted_filtered.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_legacy_spaces_accordingly.approved.txt
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_handle_spaces_accordingly.approved.txt
Labels: cla-signed

#761 Log _why_ an imported filter cannot be loaded...
  src/main/java/de/retest/recheck/review/ignore/io/ImportExternalFilterLoader.java
  src/test/java/de/retest/recheck/review/ignore/io/ImportExternalFilterLoaderIT.java
Labels: cla-signed

#762 Add bot account for mergify to perform actions
  .mergify.yml
Labels: cla-signed

#757 Feature/add exclude filter
  CHANGELOG.md
  src/main/java/de/retest/recheck/review/ignore/ExcludeFilter.java
  src/main/java/de/retest/recheck/review/ignore/MatcherFilter.java
  src/main/resources/default-recheck.ignore
  src/test/java/de/retest/recheck/RecheckImplIT.java
  src/test/java/de/retest/recheck/review/ignore/ExcludeFilterIT.java
  src/test/java/de/retest/recheck/review/ignore/ExcludeFilterTest.java
  src/test/java/de/retest/recheck/review/ignore/MatcherFilterIT.java
  src/test/resources/de/retest/recheck/RecheckImplIT.diff_should_ignore_everything_but_include_deleted_and_same_attributes_with_change_suffix.approved.txt
  src/test/resources/retest/recheck/de.retest.recheck.RecheckImplIT/with_exclude.check.recheck/retest.xml
Labels: cla-signed, enhancement

#765 Feature/fix disable report upload
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckImpl.java
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/test/java/de/retest/recheck/RecheckOptionsTest.java
Labels: cla-signed

#763 Feature/detect project layout
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckOptions.java
  src/main/java/de/retest/recheck/persistence/ProjectLayouts.java
  src/test/java/de/retest/recheck/RecheckOptionsIT.java
  src/test/java/de/retest/recheck/persistence/ProjectLayoutsIT.java
Labels: cla-signed, enhancement
