Repository retest/recheck, pull requests merged in 2020-05, with the labels that each got.

#726 Feature/fix change set applier
  CHANGELOG.md
  src/main/java/de/retest/recheck/SuiteAggregator.java
  src/main/java/de/retest/recheck/review/GlobalChangeSetApplier.java
  src/test/java/de/retest/recheck/review/GlobalChangeSetApplierIT.java
Labels: bug, cla-signed

#720 Attempt re-upload if report upload to rehub fails
  CHANGELOG.md
  src/main/java/de/retest/recheck/RecheckProperties.java
  src/main/java/de/retest/recheck/persistence/CloudPersistence.java
  src/main/java/de/retest/recheck/persistence/ReportUploadContainer.java
  src/main/java/de/retest/recheck/persistence/ReportUploadMetadata.java
Labels: cla-signed, enhancement

#727 Release/v1.11.0
  CHANGELOG.md
  pom.xml
Labels: cla-signed
